[workspace]
resolver = "2"
members = [
    "crates/osvwm",
    "crates/osvwm-config",
    "crates/osv-ipc",
    "crates/osv-bar",
    "crates/osv-intake",
    "crates/osv-control",
    "crates/osv-msg",
]

[workspace.package]
version = "0.1.0"
description = "OSV Workspace Management Routine - A disciplined Wayland compositor for Onyx OSV"
authors = ["Onyx Digital Dev"]
license = "GPL-3.0-or-later"
edition = "2021"
repository = "https://github.com/Onyx-Digital-Dev/OnyxWMR"
rust-version = "1.85"

[workspace.dependencies]
anyhow = "1.0.100"
bitflags = "2.10.0"
clap = { version = "4.5.54", features = ["derive"] }
insta = "1.46.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = { version = "0.1.44", features = ["max_level_trace", "release_max_level_debug"] }
tracing-subscriber = { version = "=0.3.22", features = ["env-filter"] }
tracy-client = { version = "0.18.4", default-features = false }

# Internal crates
osvwm-config = { version = "0.1.0", path = "crates/osvwm-config" }
osv-ipc = { version = "0.1.0", path = "crates/osv-ipc" }

[workspace.dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
default-features = false

[workspace.dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/smithay.git"

[profile.release]
debug = "line-tables-only"
overflow-checks = true
lto = "thin"

[profile.release.package.osvwm-config]
debug = false

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[workspace.lints.clippy]
new_without_default = "allow"
